---
development:
  cloud_name: jessicamaycreative
  api_key: '211557442743395'
  api_secret: qybFSqeivC-_YPO_IF1EcBDkjFA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: jessicamaycreative
  api_key: '211557442743395'
  api_secret: qybFSqeivC-_YPO_IF1EcBDkjFA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: jessicamaycreative
  api_key: '211557442743395'
  api_secret: qybFSqeivC-_YPO_IF1EcBDkjFA
  enhance_image_tag: true
  static_image_support: false
