---
development:
  cloud_name: <%= Rails.application.secrets["jessicamaycreative"] %>
  api_key: <%= Rails.application.secrets["api_key"] %>
  api_secret: <%= Rails.application.secrets["api_secret"] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: <%= Rails.application.secrets["jessicamaycreative"] %>
  api_key: <%= Rails.application.secrets["api_key"] %>
  api_secret: <%= Rails.application.secrets["api_secret"] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: <%= Rails.application.secrets["jessicamaycreative"] %>
  api_key: <%= Rails.application.secrets["api_key"] %>
  api_secret: <%= Rails.application.secrets["api_secret"] %>
  enhance_image_tag: true
  static_image_support: false
